### ISSUE TITLE
Enable bookmarking

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/website#15]
Hi,

I think it could be a very cool feature if we can create URLs with filter params.

For example, the URL _https://web-frameworks-benchmark.netlify.app/result?language=crystal,ruby_ to filter results on `crystal` and `ruby`

Regards,

**Comment by SuspiciousLookingOwl** [comment]
This is already implemented in compare page, but not implemented in result page yet.

I will probably also add query parameter for history sha like *https://web-frameworks-benchmark.netlify.app/result?language=crystal,ruby&history=5d43d8e*

**Comment by SuspiciousLookingOwl** [comment]
### Note for History Parameter

History query parameter (`?sha=...`) is currently available for dev purpose, you can manually add `sha` query parameter to the URL like  `/?sha={7_first_sha_chars}`, for example: https://web-frameworks-benchmark.netlify.app/result?sha=5d43d8e

Currently it's useful to fetch old history (useful when we already have many histories of `data.min.json`, because at some point we will have many histories of `data.min.json` and I will need to limit the max commits history shown on dropdown select on the website)

For now I will think of a better way to sync the `sha` query parameter with history dropdown select (or should I do it at all)
